# Generated by Django 5.1.2 on 2024-11-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
    ]
